### ISSUE TITLE
Error loading data

### ISSUE THREAD

**Issue by rabernat** [SophKJ/rces-final-fall21#1]
I attempted to run your notebook but encountered an error in the second cell:

```python
doi = "doi:10.5281/zenodo.5764953"
fname = "FireCounts.xlsx.csv"
file_path = pooch.retrieve(
    url=f"{doi}/{fname}",
    known_hash="md5:52e8a53cbabd01f05fc919a2927b2675",
)
file_path

import pandas as pd
df = pd.read_csv('FireCounts.xlsx.csv', delimiter=',')
print(df.head(5))
```

```
Downloading data from 'doi:10.5281/zenodo.5764953/FireCounts.xlsx.csv' to file '/home/jovyan/.cache/pooch/8ca10961ff40ba225071043f88704612-FireCounts.xlsx.csv'.
...
FileNotFoundError: [Errno 2] No such file or directory: 'FireCounts.xlsx.csv'
```

The problem is that you are passing the string `'FireCounts.xlsx.csv'` directly to `read_csv`. Instead, you need to pass the variable `file_path`. I imagine that this worked for you because you manually downloaded / copied the file `FireCounts.xlsx.csv` into the directory where the notebook is running.

If you can fix this tiny error and push changes to your repo, I will not deduct points.

**Comment by SophKJ** [comment]
This error should be fixed now!

**Comment by rabernat** [comment]
Actually, I just hit another error

```python
fire_daily_2015 = xr.open_dataset('GEOSCarb_CASAGFED3v3_Fire.Daily.x720_y360.2015.nc') 
```

> FileNotFoundError: [Errno 2] No such file or directory: b'/home/jovyan/SophKJ/rces-final-fall21/GEOSCarb_CASAGFED3v3_Fire.Daily.x720_y360.2015.nc'

A good way to check against all these errors would be to remove all the files from your project directory besides your notebook and your readme. Then "restart and run all cells". You will see if there are any more errors.

Please let me know once you have done this and pushed the changes.

**Comment by SophKJ** [comment]
@rabernat - All of the data should now be able to be opened from any directory. Sorry about this additional error, I had forgotten to delete that cell.
